### PR TITLE
Add FTS5 feature

### PR DESCRIPTION
**Pull request by jdmichaud**
I propose to add a feature to enable [FTS5](https://www.sqlite.org/fts5.html) in sqlite build.
Let me know what you think.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Hello, thank you for the pull request. There are many extrensions, and it is arguably not scalable to keep on adding feature flags. Perhaps one can allow for arbitrary directives to be passed from the environment. One could, for instance, iterate over all environment variable, and those that start with `SQLITE_` could result in a `build.define(name, value)`.

**Comment by IvanUkhov** [comment]
One concern is that it will not work in libraries, as you cannot control the environment there. But it should work for binaries. What is your use case?

**Comment by jdmichaud** [comment]
I have an application. I will configure `.cargo/config.toml` with the env var. Not my preferred solution but it works.

Note that if you are concerned with adding only this feature without all the others, I can take the time to list all the compile time features of sqlite and add them as features in this repo's `Cargo.toml`.

**Comment by IvanUkhov** [comment]
I think it is worth keeping these changes regardless.

**Pull request merged**
